spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_FIRST_LOGIN}
  threshold-ms: ${JWT_THRESHOLD_MIN_MS_FOR_REFRESH}
  refresh-ms: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    root: ${LOGGING_ROOT_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [correlationId=%X{correlationId}] %msg%n"