POSTGRES_URL: jdbc:postgresql://localhost:5432/marbl
POSTGRES_USER: marbl_u
POSTGRES_PASSWORD: marbl_psw

REDIS_HOST: localhost
REDIS_PORT: 6379

JWT_SECRET: 649cd3fa8b0349001f6bbd69f1dcbbfa25b098bb7bd95b4d9a36688dcf7a0556

KAFKA_HOST: localhost:9092

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true