spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}



logging:
  level:
    root: ${LOGGING_ROOT_LEVEL:INFO}