services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: marbl_u
      POSTGRES_PASSWORD: marbl_psw
      POSTGRES_DB: marbl
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: